name: cibpm
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  camera: ^0.10.5+5
  connectivity_plus: ^5.0.2
  dio: ^5.3.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  image: ^4.1.3
  image_picker: ^1.0.4
  path: ^1.8.3
  path_provider: ^2.1.1

  video_compress: ^3.1.2
  video_player: ^2.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
